import { connectCorridor } from '@glyphrogue/core';
import {
  getCompositionGenerator,
  PLACEHOLDER_WFC_TILES,
  PLACEHOLDER_WFC_ADJACENCY,
  PLACEHOLDER_BIOMES,
} from './compositionGenerators.js';
import { isValidExportName } from './mapEditorExport.js';

// Step-list mutations (docs/design/editor.md: "an ordered step list, not a
// new selection mechanism") - plain array helpers, no mutation of the input,
// same controlled-component convention NarrowForm.svelte's onChange follows.
export function addStep(steps, step) {
  return [...steps, step];
}

export function removeStep(steps, index) {
  return steps.filter((_, i) => i !== index);
}

export function moveStep(steps, index, direction) {
  const target = index + direction;
  if (target < 0 || target >= steps.length) return steps;
  const next = [...steps];
  [next[index], next[target]] = [next[target], next[index]];
  return next;
}

// Runtime execution path (the live-preview composer): runs each step's
// generator against the shared zone in order, auto-connecting consecutive
// steps via connectCorridor from the second step onward - editor.md's
// "regions auto-connect in step order, no manual point-picking".
export function composeZone(zone, rng, steps) {
  let previousEntryPoint = null;
  for (const step of steps) {
    const generator = getCompositionGenerator(step.generatorId);
    const entryPoint = generator.run(zone, rng, step.region, step.params);
    if (previousEntryPoint) connectCorridor(zone, previousEntryPoint, entryPoint);
    previousEntryPoint = entryPoint;
  }
  return zone;
}

export { isValidExportName };

export function composedGeneratorPath(name) {
  return `src/generators/composed/${name}.js`;
}

const CODEGEN_IMPORT_NAMES = {
  bsp: ['carveBsp'],
  'cellular-automata': ['carveCellularAutomata', 'nearestOpenCell'],
  wfc: ['collapseWfc'],
  'layered-biome': ['partitionBiomes'],
};

function paramsLiteral(params) {
  return Object.entries(params ?? {})
    .map(([key, value]) => `${key}: ${JSON.stringify(value)}`)
    .join(', ');
}

// entryPoint-yielding steps assign straight from the call's own return
// value; carveCellularAutomata mutates in place and returns nothing, so its
// source line pair mirrors compositionGenerators.js's own run() wrapper -
// call, then derive via nearestOpenCell.
function emitStepSource(step) {
  const regionLiteral = JSON.stringify(step.region);
  const params = paramsLiteral(step.params);

  switch (step.generatorId) {
    case 'bsp':
      return `  entryPoint = carveBsp(zone, rng, { region: ${regionLiteral}, ${params} }).entryPoint;`;
    case 'cellular-automata':
      return (
        `  carveCellularAutomata(zone, rng, { region: ${regionLiteral}, ${params} });\n` +
        `  entryPoint = nearestOpenCell(zone, ${regionLiteral});`
      );
    case 'wfc':
      return `  entryPoint = collapseWfc(zone, rng, { region: ${regionLiteral}, tiles: WFC_TILES, adjacency: WFC_ADJACENCY, ${params} }).entryPoint;`;
    case 'layered-biome':
      return `  entryPoint = partitionBiomes(zone, rng, { region: ${regionLiteral}, biomes: BIOMES, ${params} }).entryPoint;`;
    default:
      throw new Error(`generateComposedSource: unknown generatorId "${step.generatorId}"`);
  }
}

// Codegen path: emits a plain .js module - a single default-exported
// generatorFn(ctx) (matching every real generator's actual signature -
// bspGenerator/cellularAutomataGenerator/wfcGenerator/layeredBiomeGenerator
// all take ctx.params/ctx.rng, not the (zone, rng, options) editor.md's
// prose describes) whose body is a literal, readable sequence of the
// recorded steps' calls followed by their connectCorridor calls in order.
// Self-contained: WFC/layered-biome placeholder tiles/adjacency/biomes are
// inlined as local consts (with the same "testing boilerplate" warning
// compositionGenerators.js carries) rather than imported from this editor
// package, since the emitted file ships independently of the editor.
export function generateComposedSource(steps, { width, height }) {
  const usedGeneratorIds = new Set(steps.map((step) => step.generatorId));
  const usesWfc = usedGeneratorIds.has('wfc');
  const usesLayeredBiome = usedGeneratorIds.has('layered-biome');

  const importNames = new Set(['createZone', 'connectCorridor']);
  for (const id of usedGeneratorIds) {
    for (const name of CODEGEN_IMPORT_NAMES[id] ?? []) importNames.add(name);
  }

  const lines = [];
  lines.push(
    '// Generated by the generator composition tool (docs/design/editor.md).',
    '// Re-seeded fresh every generation - not a frozen captured layout.',
    `import { ${[...importNames].join(', ')} } from '@glyphrogue/core';`,
    ''
  );

  if (usesWfc) {
    lines.push(
      '// TESTING BOILERPLATE: placeholder WFC tiles/adjacency, not an',
      '// authored tileset - replace before shipping.',
      `const WFC_TILES = ${JSON.stringify(PLACEHOLDER_WFC_TILES)};`,
      `const WFC_ADJACENCY = ${JSON.stringify(PLACEHOLDER_WFC_ADJACENCY)};`,
      ''
    );
  }

  if (usesLayeredBiome) {
    lines.push(
      '// TESTING BOILERPLATE: placeholder biomes, not authored content -',
      '// replace before shipping.',
      `const BIOMES = ${JSON.stringify(PLACEHOLDER_BIOMES)};`,
      ''
    );
  }

  lines.push(
    'export default function generatorFn(ctx) {',
    '  const { rng } = ctx;',
    `  const zone = createZone(${JSON.stringify(width)}, ${JSON.stringify(height)});`,
    '  let entryPoint;',
    '  let previousEntryPoint;',
    ''
  );

  steps.forEach((step, index) => {
    lines.push(emitStepSource(step));
    if (index > 0) lines.push('  connectCorridor(zone, previousEntryPoint, entryPoint);');
    lines.push('  previousEntryPoint = entryPoint;', '');
  });

  lines.push('  return zone;', '}', '');

  return lines.join('\n');
}
